language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install: pip install flake8 coverage coveralls

script: ./runtests.sh

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
