#!/usr/bin/env python3
import os
import shutil
import sys
from bgwgen import bgw
from bgwgen import parser
from bgwgen import qe


def copy_templates(current='.'):
    temp_dir = 'templates'
    temp_current = os.path.join(temp_dir, current)

    if os.path.isdir(temp_current):
        for f in os.listdir(temp_current):
            new_current = os.path.join(current, f)

            if os.path.isdir(os.path.join(temp_current, f)):
                if not os.path.isdir(new_current):
                    shutil.copytree(os.path.join(temp_current, f), new_current)
                else:
                    copy_templates(new_current)
            elif os.path.isfile(os.path.join(temp_current, f)):
                shutil.copy(os.path.join(temp_current, f), new_current)


if __name__ == "__main__":
    config = parser.parse(sys.argv[1])
    qe.create_qe(config)
    bgw.create_bgw(config)
    copy_templates()
